'use client'

import { ServicePageLayout } from '@/components/ServicePageLayout';
import { Waves, Star, Zap, Droplet } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import { ServiceCard } from '@/components/ServiceCard';

const Kavitation = () => {
  const { isGerman } = useLanguage();

  // Recommended body contouring services
  const RecommendedServices = () => (
    <div className="mt-12">
      <h2 className="text-2xl md:text-3xl font-heading font-semibold text-brand-espresso mb-6 text-center">
        {isGerman ? 'Empfohlene Kombinationen' : 'Рекомендуемые комбинации'}
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <ServiceCard
          title="RF-Vakuum"
          description={isGerman ? 'Radiofrequenz mit Vakuum für Cellulite-Reduktion' : 'Радиочастоты с вакуумом для уменьшения целлюлита'}
          icon={Star}
          href="/services/koerperbehandlungen/rf-vakuum"
          image="/83.jpg"
        />
        <ServiceCard
          title="RF-Lifting"
          description={isGerman ? 'Radiofrequenz für Hautstraffung' : 'Радиочастоты для подтяжки кожи'}
          icon={Zap}
          href="/services/apparative-anti-aging/rf-lifting"
          image="/162.jpeg"
        />
        <ServiceCard
          title={isGerman ? 'Ultraschall' : 'Ультразвук'}
          description={isGerman ? 'Tiefenwirksame Hautpflege' : 'Глубокий уход за кожей'}
          icon={Droplet}
          href="/services/apparative-anti-aging/ultraschall"
          image="/126.jpeg"
        />
      </div>
    </div>
  );

  return (
    <ServicePageLayout
      icon={Waves}
      title={isGerman ? "Ultraschallkavitation in München — sicheres Body-Contouring ohne Operation" : "Кавитация в Мюнхене — безопасное моделирование тела с помощью ультразвука"}
      subtitle={isGerman ? "Effektive Fettreduktion und Körperformung mit modernster Ultraschalltechnologie in München-Haidhausen" : "Эффективная коррекция фигуры и моделирование тела с помощью современной ультразвуковой технологии в Мюнхене-Хайдхаузен"}
      aboutTitle={isGerman ? "Was ist Ultraschallkavitation?" : "Что такое ультразвуковая кавитация"}
      aboutDescription={[
        isGerman
          ? 'Ultraschallkavitation (auch Fett-Kavitation oder Lipolyse genannt) ist eine moderne, hochwirksame und völlig nicht-invasive apparative Methode zur gezielten Reduktion lokaler Fettdepots und zur Körperkonturierung. In unserem Kosmetikstudio in München-Haidhausen setzen wir professionelle Kavitationsgeräte der neuesten Generation ein, die niederfrequenten Ultraschall (typischerweise 28–40 kHz) zur sanften, aber effektiven Zerstörung von Fettzellen nutzen — ohne Operation, ohne Schnitte, ohne Injektionen und ohne Ausfallzeiten.'
          : 'Ультразвуковая кавитация (также называется жировая кавитация или липолиз) — это современный, высокоэффективный и полностью неинвазивный аппаратный метод целенаправленного уменьшения локальных жировых отложений и коррекции контуров тела. В нашей косметологической студии в Мюнхене-Хайдхаузен мы применяем профессиональное кавитационное оборудование нового поколения, которое использует низкочастотный ультразвук (обычно 28–40 кГц) для мягкого, но эффективного разрушения жировых клеток — без операции, без разрезов, без инъекций и без периода реабилитации.',

        isGerman
          ? 'Wie funktioniert die Kavitation? Die niederfrequenten Ultraschallwellen dringen tief in das Unterhautfettgewebe (Hypodermis) ein und erzeugen dort einen physikalischen Effekt namens „Kavitation": Es entstehen mikroskopisch kleine Gasblasen (Kavitationsblasen) innerhalb und zwischen den Fettzellen. Diese Blasen expandieren und kollabieren schnell (implodieren), wodurch ein Druckwechsel entsteht, der die Membran der Fettzellen (Adipozyten) destabilisiert und auflöst. Das in den Fettzellen gespeicherte Fett (Triglyceride) wird freigesetzt und in kleinere Moleküle (freie Fettsäuren und Glycerin) zerlegt.'
          : 'Как работает кавитация? Низкочастотные ультразвуковые волны проникают глубоко в подкожную жировую ткань (гиподерму) и создают там физический эффект под названием «кавитация»: возникают микроскопические газовые пузырьки (кавитационные пузырьки) внутри и между жировыми клетками. Эти пузырьки быстро расширяются и схлопываются (имплодируют), создавая перепад давления, который дестабилизирует и разрушает мембрану жировых клеток (адипоцитов). Хранящийся в жировых клетках жир (триглицериды) высвобождается и расщепляется на более мелкие молекулы (свободные жирные кислоты и глицерин).',

        isGerman
          ? 'Die freigesetzten Fettsäuren und Glycerin werden anschließend vom Körper auf natürlichem Wege verarbeitet und ausgeschieden: über das Lymphsystem abtransportiert, in die Leber gebracht, dort verstoffwechselt und schließlich über die Nieren und den Darm ausgeschieden. Dieser Prozess dauert 3–7 Tage nach jeder Behandlung. Daher ist es wichtig, nach der Kavitation ausreichend Wasser zu trinken (mind. 2 Liter täglich), sich moderat zu bewegen (Spaziergang, leichter Sport) und auf eine gesunde Ernährung zu achten, um den Fettabbau zu beschleunigen und zu unterstützen.'
          : 'Высвобожденные жирные кислоты и глицерин затем естественным образом перерабатываются и выводятся организмом: транспортируются через лимфатическую систему, попадают в печень, там метаболизируются и в конечном итоге выводятся через почки и кишечник. Этот процесс занимает 3–7 дней после каждой процедуры. Поэтому важно после кавитации пить достаточно воды (мин. 2 литра в день), умеренно двигаться (прогулки, лёгкий спорт) и придерживаться здорового питания, чтобы ускорить и поддержать липолиз.',

        isGerman
          ? 'Im Gegensatz zur operativen Fettabsaugung (Liposuktion) ist die Ultraschallkavitation völlig nicht-invasiv, schmerzfrei, sicher und ohne Ausfallzeiten. Es gibt keine Narben, keine Blutergüsse, keine Schwellungen und kein Risiko für Komplikationen wie Infektionen oder Anästhesierisiken. Die Behandlung ist ideal für Menschen, die hartnäckige Fettpolster („Problemzonen") haben, die sich trotz gesunder Ernährung und regelmäßigem Sport nicht reduzieren lassen. Die Kavitation ist keine Methode zur Gewichtsreduktion bei starkem Übergewicht, sondern eine Methode zur gezielten Körperkonturierung und Formung bei normalem oder leicht erhöhtem Body-Mass-Index (BMI 18–30).'
          : 'В отличие от операционной липосакции, ультразвуковая кавитация полностью неинвазивна, безболезненна, безопасна и без периода реабилитации. Нет рубцов, синяков, отёков и риска осложнений, таких как инфекции или риски анестезии. Процедура идеальна для людей, у которых есть упорные жировые отложения («проблемные зоны»), которые не уменьшаются несмотря на здоровое питание и регулярные занятия спортом. Кавитация — это не метод похудения при сильном избыточном весе, а метод целенаправленной коррекции контуров тела и формирования при нормальном или слегка повышенном индексе массы тела (ИМТ 18–30).',

        isGerman
          ? 'In unserem Kosmetikstudio in München bieten wir Ultraschallkavitation für alle typischen Problemzonen an: Bauch (Oberbauch, Unterbauch, seitlicher Bauch/"Love Handles"), Hüften („Reiterhosen"), Oberschenkel (Innen- und Außenseite), Gesäß, Arme (Oberarme/"Winkearme"), Knie (über den Knien) und Rücken (unterer Rücken). Die Behandlung kann einzeln oder in Kombination mit anderen Methoden (RF-Lifting für Hautstraffung, Vakuum-Therapie für Lymphdrainage, LED-Lichttherapie für Regeneration) durchgeführt werden, um maximale Ergebnisse zu erzielen. Viele unserer Kunden aus München und Umgebung wählen die Kavitation als effektivste und sicherste nicht-invasive Alternative zur Fettabsaugung.'
          : 'В нашей косметологической студии в Мюнхене мы предлагаем ультразвуковую кавитацию для всех типичных проблемных зон: живот (верхний живот, нижний живот, боковой живот/"ушки"), бёдра («галифе»), бедра (внутренняя и наружная сторона), ягодицы, руки (плечи/"крылья"), колени (над коленями) и спина (нижняя часть спины). Процедура может проводиться отдельно или в комбинации с другими методами (RF-лифтинг для подтяжки кожи, вакуумная терапия для лимфодренажа, светотерапия для регенерации) для достижения максимальных результатов. Многие наши клиенты из Мюнхена и окрестностей выбирают кавитацию как самую эффективную и безопасную неинвазивную альтернативу липосакции.'
      ]}
      benefits={[
        isGerman ? 'Gezielte Reduktion lokaler Fettdepots ohne Operation und ohne Schnitte' : 'Целенаправленное уменьшение локальных жировых отложений без операции и без разрезов',
        isGerman ? 'Umfangsreduktion von 2–6 cm pro Behandlungszone (je nach Ausgangsvolumen)' : 'Уменьшение объёмов на 2–6 см за зону обработки (в зависимости от начального объёма)',
        isGerman ? 'Körperkonturierung und Modellierung der Silhouette' : 'Коррекция контуров тела и моделирование силуэта',
        isGerman ? 'Reduzierung hartnäckiger Fettpolster an Bauch, Hüften, Oberschenkeln, Gesäß, Armen' : 'Уменьшение упорных жировых отложений на животе, бёдрах, галифе, ягодицах, руках',
        isGerman ? 'Verbesserung der Hautstruktur und Reduzierung von Cellulite ("Orangenhaut")' : 'Улучшение структуры кожи и уменьшение целлюлита ("апельсиновой корки")',
        isGerman ? 'Straffung der Haut und Verbesserung der Hautqualität' : 'Подтяжка кожи и улучшение качества кожи',
        isGerman ? 'Aktivierung des Lymphsystems und Entgiftung' : 'Активация лимфатической системы и детоксикация',
        isGerman ? 'Verbesserung der Mikrozirkulation und des Stoffwechsels' : 'Улучшение микроциркуляции и метаболизма',
        isGerman ? 'Völlig schmerzfrei und entspannend' : 'Абсолютно безболезненно и расслабляюще',
        isGerman ? 'Keine Narben, keine Blutergüsse, keine Schwellungen' : 'Без рубцов, без синяков, без отёков',
        isGerman ? 'Keine Ausfallzeiten — sofort zurück zum normalen Alltag' : 'Без периода реабилитации — сразу возврат к обычной жизни',
        isGerman ? 'Keine Anästhesie, keine Injektionen, keine Risiken' : 'Без анестезии, без инъекций, без рисков',
        isGerman ? 'Natürliche, sichere Alternative zur Liposuktion (Fettabsaugung)' : 'Естественная, безопасная альтернатива липосакции',
        isGerman ? 'Kombinierbar mit RF-Lifting, Vakuum-Therapie und Lymphdrainage für maximale Wirkung' : 'Можно комбинировать с RF-лифтингом, вакуумной терапией и лимфодренажем для максимального эффекта',
        isGerman ? 'Geeignet für Frauen und Männer mit BMI 18–30' : 'Подходит для женщин и мужчин с ИМТ 18–30',
        isGerman ? 'Sofort sichtbare Ergebnisse nach 3–4 Behandlungen' : 'Сразу видимые результаты после 3–4 процедур',
        isGerman ? 'Langfristige Ergebnisse bei gesunder Lebensweise' : 'Долгосрочные результаты при здоровом образе жизни'
      ]}
      steps={[
        {
          title: isGerman ? '1. Kostenlose Beratung, Körperanalyse und Vermessung' : '1. Бесплатная консультация, анализ тела и замеры',
          description: isGerman
            ? 'Zu Beginn analysieren wir Ihre Körperkonstitution, Ihren BMI und Ihre individuellen Behandlungsziele. Wir besprechen, welche Problemzonen Sie behandeln möchten (Bauch, Hüften, Oberschenkel, Gesäß, Arme, Knie, Rücken) und welche Ergebnisse realistisch erreichbar sind. Wir messen die Umfänge der Behandlungszonen (mit Maßband), machen optional Fotos für den Vorher-Nachher-Vergleich und klären alle Fragen zu Ablauf, Wirkung, empfohlener Anzahl der Sitzungen und möglichen Kombinationen mit anderen Behandlungen (RF-Lifting, Vakuum-Therapie, Lymphdrainage). Alle Kontraindikationen werden besprochen.'
            : 'В начале мы анализируем вашу конституцию тела, ИМТ и индивидуальные цели. Обсуждаем, какие проблемные зоны вы хотите обработать (живот, бёдра, галифе, ягодицы, руки, колени, спина) и какие результаты реально достижимы. Мы измеряем объёмы зон обработки (сантиметровой лентой), опционально делаем фото для сравнения до/после и отвечаем на все вопросы о процедуре, эффекте, рекомендуемом количестве сеансов и возможных комбинациях с другими процедурами (RF-лифтинг, вакуумная терапия, лимфодренаж). Обсуждаем все противопоказания.'
        },
        {
          title: isGerman ? '2. Vorbereitung der Behandlungszone' : '2. Подготовка зоны обработки',
          description: isGerman
            ? 'Die Behandlungszone wird sanft gereinigt und von Cremes, Ölen oder Schweiß befreit. Eine saubere Haut ist wichtig für die optimale Übertragung der Ultraschallwellen. Anschließend wird ein spezielles Ultraschall-Kontaktgel aufgetragen, das die Kavitationswellen optimal überträgt und ein angenehmes Gleiten des Kavitationskopfes ermöglicht. Wir markieren die zu behandelnden Zonen und legen Sie bequem hin.'
            : 'Зона обработки деликатно очищается от кремов, масел или пота. Чистая кожа важна для оптимальной передачи ультразвуковых волн. Затем наносится специальный ультразвуковой контактный гель, который оптимально передаёт кавитационные волны и обеспечивает комфортное скольжение кавитационной насадки. Мы отмечаем зоны для обработки и укладываем вас удобно.'
        },
        {
          title: isGerman ? '3. Ultraschall-Kavitation (30-60 Minuten)' : '3. Ультразвуковая кавитация (30-60 минут)',
          description: isGerman
            ? 'Mit einem speziellen Kavitationskopf (Handstück) werden sanfte, kreisende Bewegungen über die Fettzone ausgeführt. Die niederfrequenten Ultraschallwellen (28–40 kHz) dringen tief in das Fettgewebe ein und erzeugen dort Kavitationsblasen, die die Fettzellen zerstören. Sie spüren während der Behandlung ein leichtes Summen oder Vibrieren, eventuell eine sanfte Wärme — keine Schmerzen, kein Brennen. Die Behandlung ist völlig schmerzfrei und wird von den meisten Kunden als angenehm und entspannend empfunden. Die Behandlungsdauer variiert je nach Zone und Größe: Eine kleine Zone (Knie, Oberarme) dauert 30 Min., eine mittlere Zone (Bauch, Gesäß) dauert 40–45 Min., zwei Zonen dauern 60 Min. Wir behandeln maximal 1–2 Zonen pro Sitzung, um das Lymphsystem nicht zu überlasten.'
            : 'Специальной кавитационной насадкой выполняются мягкие круговые движения по жировой зоне. Низкочастотные ультразвуковые волны (28–40 кГц) проникают глубоко в жировую ткань и создают там кавитационные пузырьки, которые разрушают жировые клетки. Во время процедуры вы чувствуете лёгкое жужжание или вибрацию, возможно лёгкое тепло — без боли, без жжения. Процедура абсолютно безболезненна и большинством клиентов воспринимается как приятная и расслабляющая. Продолжительность зависит от зоны и размера: малая зона (колени, плечи) 30 мин., средняя зона (живот, ягодицы) 40–45 мин., две зоны 60 мин. Мы обрабатываем максимум 1–2 зоны за сеанс, чтобы не перегружать лимфатическую систему.'
        },
        {
          title: isGerman ? '4. Nachbehandlung und optionale Kombinationen' : '4. Последующий уход и опциональные комбинации',
          description: isGerman
            ? 'Nach der Kavitation ist es wichtig, den Fettabbau zu unterstützen und zu beschleunigen. Optional kann die Kavitation mit anderen Behandlungen kombiniert werden, um den Effekt zu maximieren: Lymphdrainage-Massage (um den Abtransport der Fettsäuren über die Lymphe zu beschleunigen), RF-Lifting (für zusätzliche Hautstraffung und Verbesserung der Hautqualität), Vakuum-Therapie (für verstärkte Durchblutung und Anti-Cellulite-Wirkung) oder Kryotherapie (zur Verstärkung des Fettabbaus und Straffung). Wir beraten Sie gerne zu den besten Kombinationen für Ihre Körperformungsziele. Nach der Behandlung sollten Sie sofort 1–2 Gläser Wasser trinken.'
            : 'После кавитации важно поддержать и ускорить липолиз. Опционально кавитацию можно комбинировать с другими процедурами для максимизации эффекта: лимфодренажный массаж (для ускорения выведения жирных кислот через лимфу), RF-лифтинг (для дополнительной подтяжки кожи и улучшения качества кожи), вакуумная терапия (для усиленного кровообращения и антицеллюлитного эффекта) или криотерапия (для усиления липолиза и подтяжки). Мы с радостью проконсультируем вас по лучшим комбинациям для ваших целей коррекции фигуры. После процедуры следует сразу выпить 1–2 стакана воды.'
        },
        {
          title: isGerman ? '5. Empfehlungen für zu Hause und Behandlungsplan' : '5. Рекомендации для дома и план процедур',
          description: isGerman
            ? 'Sie erhalten detaillierte Empfehlungen für die Zeit nach der Behandlung, um den Fettabbau optimal zu unterstützen: Viel Wasser trinken (mind. 2–3 Liter täglich), gesunde, fettarme Ernährung (Gemüse, Obst, mageres Protein), moderate Bewegung (30 Min. Spaziergang, leichtes Cardio, Yoga), Alkohol 48 Stunden meiden (Alkohol verlangsamt den Fettabbau durch die Leber). Für optimale und langanhaltende Ergebnisse empfehlen wir eine Kur von 8–12 Behandlungen, idealerweise 1× pro Woche (mind. 5–7 Tage Abstand zwischen den Sitzungen). Die Ergebnisse sind kumulativ — je mehr Behandlungen, desto mehr Fettreduktion. Nach Abschluss der Kur empfehlen wir Erhaltungsbehandlungen alle 2–3 Monate, um das Ergebnis langfristig zu bewahren.'
            : 'Вы получаете детальные рекомендации для периода после процедуры, чтобы оптимально поддержать липолиз: пить много воды (мин. 2–3 литра в день), здоровое питание с низким содержанием жиров (овощи, фрукты, нежирный белок), умеренное движение (30 мин. прогулки, лёгкое кардио, йога), избегать алкоголя 48 часов (алкоголь замедляет липолиз через печень). Для оптимального и долговременного результата мы рекомендуем курс из 8–12 процедур, в идеале 1× в неделю (мин. 5–7 дней перерыв между сеансами). Результаты кумулятивные — чем больше процедур, тем больше уменьшение жира. После завершения курса рекомендуем поддерживающие сеансы каждые 2–3 месяца для долгосрочного сохранения результата.'
        }
      ]}
      additionalSections={<RecommendedServices />}
      priceSection="body-treatments"
      contraindications={[
        isGerman ? 'Schwangerschaft und Stillzeit' : 'Беременность и кормление грудью',
        isGerman ? 'Herzschrittmacher oder implantierte elektronische Geräte' : 'Кардиостимулятор или имплантированные электронные устройства',
        isGerman ? 'Leber- oder Nierenerkrankungen (Fettstoffwechsel wird über Leber/Nieren abgebaut)' : 'Заболевания печени или почек (метаболизм жиров происходит через печень/почки)',
        isGerman ? 'Diabetes oder schwere Stoffwechselerkrankungen' : 'Диабет или тяжёлые метаболические заболевания',
        isGerman ? 'Thrombose, Krampfadern oder schwere Venenerkrankungen im Behandlungsbereich' : 'Тромбоз, варикоз или тяжёлые заболевания вен в зоне обработки',
        isGerman ? 'Krebs, Chemotherapie oder Strahlentherapie' : 'Онкология, химиотерапия или лучевая терапия',
        isGerman ? 'Epilepsie oder neurologische Erkrankungen' : 'Эпилепсия или неврологические заболевания',
        isGerman ? 'Frische Operationen im Behandlungsbereich (mind. 6 Monate Abstand)' : 'Недавние операции в зоне обработки (мин. 6 месяцев после)',
        isGerman ? 'Metallimplantate, Spirale oder andere Fremdkörper im Behandlungsbereich' : 'Металлические имплантаты, спираль или другие инородные тела в зоне обработки',
        isGerman ? 'Hautinfektionen, Entzündungen oder offene Wunden' : 'Кожные инфекции, воспаления или открытые раны',
        isGerman ? 'BMI über 30 (Kavitation ist keine Methode zur Gewichtsreduktion bei Adipositas)' : 'ИМТ выше 30 (кавитация не является методом похудения при ожирении)'
      ]}
      faq={[
        {
          q: isGerman ? 'Wie viele Kavitationsbehandlungen brauche ich für sichtbare Ergebnisse?' : 'Сколько процедур кавитации нужно для видимого результата?',
          a: isGerman
            ? 'Für optimale und langanhaltende Ergebnisse empfehlen wir eine Kur von 8–12 Behandlungen, idealerweise 1× pro Woche (mind. 5–7 Tage Abstand zwischen den Sitzungen). Erste sichtbare Ergebnisse (Umfangsreduktion) zeigen sich oft bereits nach 3–4 Behandlungen — die Haut wirkt straffer, glatter und die Problemzone kleiner. Die volle Wirkung entfaltet sich über die gesamte Kur: Im Durchschnitt können Sie mit einer Umfangsreduktion von 2–6 cm pro Behandlungszone rechnen (abhängig von Ausgangsvolumen, Hauttyp, Lebensweise). Die Ergebnisse sind kumulativ — je mehr Behandlungen, desto mehr Fettreduktion. Nach Abschluss der Kur empfehlen wir Erhaltungsbehandlungen alle 2–3 Monate, um das Ergebnis langfristig zu bewahren (besonders wichtig bei genetisch bedingten Problemzonen).'
            : 'Для оптимального и долговременного результата мы рекомендуем курс из 8–12 процедур, в идеале 1× в неделю (мин. 5–7 дней перерыв между сеансами). Первые видимые результаты (уменьшение объёмов) часто заметны уже после 3–4 процедур — кожа выглядит более упругой, гладкой, а проблемная зона меньше. Полный эффект развивается в течение всего курса: в среднем вы можете рассчитывать на уменьшение объёмов на 2–6 см за зону обработки (в зависимости от начального объёма, типа кожи, образа жизни). Результаты кумулятивные — чем больше процедур, тем больше уменьшение жира. После завершения курса рекомендуем поддерживающие сеансы каждые 2–3 месяца для долгосрочного сохранения результата (особенно важно при генетически обусловленных проблемных зонах).'
        },
        {
          q: isGerman ? 'Ist die Ultraschallkavitation schmerzhaft?' : 'Ультразвуковая кавитация болезненна?',
          a: isGerman
            ? 'Nein, die Ultraschallkavitation ist völlig schmerzfrei und wird von den meisten Kunden als angenehm und entspannend empfunden. Während der Behandlung spüren Sie lediglich ein leichtes Summen oder Vibrieren des Ultraschallkopfes, eventuell eine sanfte Wärme im Gewebe — aber keine Schmerzen, kein Brennen, kein Stechen. Manche Kunden berichten von einem leichten Kribbeln oder „innerlichen Vibrieren" — dies ist völlig normal und zeigt, dass die Kavitation wirkt. Im Vergleich zu invasiven Methoden (Liposuktion mit Anästhesie, Schmerzen, Schwellungen) ist die Kavitation deutlich angenehmer und stressfreier. Es gibt keine Nadeln, keine Schnitte, keine Blutergüsse. Die Behandlung ist so komfortabel, dass viele Kunden dabei entspannen oder sogar schlafen.'
            : 'Нет, ультразвуковая кавитация абсолютно безболезненна и большинством клиентов воспринимается как приятная и расслабляющая. Во время процедуры вы чувствуете лишь лёгкое жужжание или вибрацию ультразвуковой насадки, возможно лёгкое тепло в ткани — но без боли, без жжения, без покалывания. Некоторые клиенты отмечают лёгкое покалывание или «внутреннюю вибрацию» — это совершенно нормально и показывает, что кавитация работает. По сравнению с инвазивными методами (липосакция с анестезией, болями, отёками) кавитация значительно приятнее и менее стрессовая. Нет игл, разрезов, синяков. Процедура настолько комфортна, что многие клиенты расслабляются или даже спят.'
        },
        {
          q: isGerman ? 'Wohin geht das Fett nach der Kavitation?' : 'Куда девается жир после кавитации?',
          a: isGerman
            ? 'Das durch die Kavitation freigesetzte Fett (Triglyceride werden in Fettsäuren und Glycerin zerlegt) wird vom Körper auf natürlichem Wege verarbeitet und ausgeschieden: Die Fettsäuren und Glycerin werden über das Lymphsystem abtransportiert, gelangen über die Blutbahn in die Leber, werden dort verstoffwechselt (in Energie umgewandelt oder zur Ausscheidung vorbereitet) und schließlich über die Nieren (Urin) und den Darm ausgeschieden. Dieser Prozess dauert 3–7 Tage nach jeder Behandlung. Daher ist es wichtig, nach der Kavitation ausreichend Wasser zu trinken (mind. 2–3 Liter täglich), sich moderat zu bewegen (um Lymphe und Kreislauf anzuregen) und Alkohol 48 Stunden zu meiden (Alkohol verlangsamt den Fettabbau in der Leber). Je besser Sie diese Empfehlungen befolgen, desto schneller und effektiver wird das Fett ausgeschieden.'
            : 'Высвобожденный в результате кавитации жир (триглицериды расщепляются на жирные кислоты и глицерин) естественным образом перерабатывается и выводится организмом: жирные кислоты и глицерин транспортируются через лимфатическую систему, попадают через кровоток в печень, там метаболизируются (превращаются в энергию или готовятся к выведению) и в конечном итоге выводятся через почки (моча) и кишечник. Этот процесс занимает 3–7 дней после каждой процедуры. Поэтому важно после кавитации пить достаточно воды (мин. 2–3 литра в день), умеренно двигаться (чтобы стимулировать лимфу и кровообращение) и избегать алкоголя 48 часов (алкоголь замедляет липолиз в печени). Чем лучше вы следуете этим рекомендациям, тем быстрее и эффективнее выводится жир.'
        },
        {
          q: isGerman ? 'Nehme ich durch Kavitation ab (verliere ich Gewicht)?' : 'Я похудею с помощью кавитации (потеряю вес)?',
          a: isGerman
            ? 'Kavitation ist keine Methode zur allgemeinen Gewichtsreduktion, sondern eine Methode zur gezielten Körperkonturierung und Formung. Sie verlieren an Umfang und Volumen in den behandelten Zonen (2–6 cm pro Zone möglich), aber nicht unbedingt viel Gewicht auf der Waage (typischerweise 1–3 kg nach einer kompletten Kur). Der Grund: Fett ist leichter als Muskeln — wenn Sie Fettvolumen verlieren, aber gleichzeitig Muskeln aufbauen (durch Sport), kann Ihr Gewicht gleich bleiben oder sogar leicht steigen, obwohl Sie schlanker und straffer aussehen. Kavitation ist ideal für Menschen mit normalem oder leicht erhöhtem BMI (18–30), die hartnäckige „Problemzonen" haben, die sich trotz gesunder Ernährung und Sport nicht reduzieren lassen. Wenn Ihr Ziel allgemeine Gewichtsabnahme bei starkem Übergewicht ist, empfehlen wir zunächst eine Ernährungsumstellung und Sport — Kavitation kann dann später zur Feinmodellierung eingesetzt werden.'
            : 'Кавитация — это не метод общего похудения, а метод целенаправленной коррекции контуров тела и формирования. Вы теряете объёмы в обработанных зонах (возможно 2–6 см на зону), но не обязательно много веса на весах (обычно 1–3 кг после полного курса). Причина: жир легче мышц — если вы теряете объём жира, но одновременно наращиваете мышцы (через спорт), ваш вес может оставаться прежним или даже слегка увеличиваться, хотя вы выглядите стройнее и подтянутее. Кавитация идеальна для людей с нормальным или слегка повышенным ИМТ (18–30), у которых есть упорные «проблемные зоны», которые не уменьшаются несмотря на здоровое питание и спорт. Если ваша цель — общее похудение при сильном избыточном весе, мы рекомендуем сначала изменить питание и заняться спортом — кавитация может затем использоваться для точной коррекции.'
        },
        {
          q: isGerman ? 'Was ist der Unterschied zwischen Kavitation und Liposuktion (Fettabsaugung)?' : 'В чём разница между кавитацией и липосакцией?',
          a: isGerman
            ? 'Der Unterschied ist grundlegend: 🔹 Liposuktion (Fettabsaugung) ist eine invasive chirurgische Operation unter Vollnarkose oder lokaler Betäubung, bei der mit Kanülen Fettzellen mechanisch abgesaugt werden. Es gibt Schnitte, Narben, Blutergüsse, Schwellungen, Schmerzen, Infektionsrisiken und 2–4 Wochen Ausfallzeit. Die Ergebnisse sind sofort sichtbar, aber radikal. 🔸 Kavitation ist eine völlig nicht-invasive, schmerzfreie Behandlung ohne Anästhesie, ohne Schnitte, ohne Nadeln, bei der Fettzellen mit Ultraschall sanft zerstört und vom Körper natürlich ausgeschieden werden. Es gibt keine Narben, keine Blutergüsse, keine Ausfallzeiten. Die Ergebnisse entwickeln sich graduell über 3–7 Tage nach jeder Sitzung. Kavitation ist die ideale Alternative für Menschen, die keine Operation wollen, keine Risiken eingehen wollen und eine natürlichere, sanftere Methode zur Körperformung suchen. Beide Methoden haben ihren Platz — bei sehr großen Fettmengen ist Liposuktion effektiver, bei lokalen Problemzonen ist Kavitation sicherer und komfortabler.'
            : 'Разница фундаментальная: 🔹 Липосакция — это инвазивная хирургическая операция под общим наркозом или местной анестезией, при которой канюлями механически отсасываются жировые клетки. Есть разрезы, рубцы, синяки, отёки, боли, риски инфекций и 2–4 недели реабилитации. Результаты видны сразу, но радикальны. 🔸 Кавитация — это полностью неинвазивная, безболезненная процедура без анестезии, без разрезов, без игл, при которой жировые клетки мягко разрушаются ультразвуком и естественным образом выводятся организмом. Нет рубцов, синяков, реабилитации. Результаты развиваются постепенно в течение 3–7 дней после каждого сеанса. Кавитация — идеальная альтернатива для тех, кто не хочет операцию, не хочет рисков и ищет более естественный, мягкий метод коррекции фигуры. Оба метода имеют своё место — при очень больших объёмах жира липосакция эффективнее, при локальных проблемных зонах кавитация безопаснее и комфортнее.'
        },
        {
          q: isGerman ? 'Kann ich Kavitation mit anderen Behandlungen kombinieren?' : 'Можно ли комбинировать кавитацию с другими процедурами?',
          a: isGerman
            ? 'Ja, Kavitation lässt sich hervorragend mit anderen Behandlungen kombinieren und die Kombination verstärkt die Wirkung erheblich! Besonders empfehlenswerte Kombinationen: 🔸 Kavitation + Lymphdrainage-Massage = beschleunigte Ausscheidung der Fettsäuren über die Lymphe, Entgiftung und Entstauung. 🔸 Kavitation + RF-Lifting Körper = Fettreduktion + Hautstraffung für optimale Körperkonturierung, besonders nach Gewichtsverlust oder Schwangerschaft. 🔸 Kavitation + Vakuum-Therapie = verstärkte Durchblutung, Anti-Cellulite-Wirkung und Lymphdrainage. 🔸 Kavitation + Kryotherapie = Verstärkung des Fettabbaus durch Kälte und zusätzliche Straffung. Die Kombinationen können individuell auf Ihre Body-Sculpting-Ziele abgestimmt werden. Wir beraten Sie gerne in unserem Studio in München-Haidhausen zu den besten Synergien für maximale Ergebnisse.'
            : 'Да, кавитацию можно отлично комбинировать с другими процедурами, и комбинация значительно усиливает эффект! Особенно рекомендуемые комбинации: 🔸 Кавитация + лимфодренажный массаж = ускоренное выведение жирных кислот через лимфу, детоксикация и снятие застоя. 🔸 Кавитация + RF-лифтинг тела = уменьшение жира + подтяжка кожи для оптимальной коррекции контуров тела, особенно после похудения или беременности. 🔸 Кавитация + вакуумная терапия = усиленное кровообращение, антицеллюлитный эффект и лимфодренаж. 🔸 Кавитация + криотерапия = усиление липолиза через холод и дополнительная подтяжка. Комбинации могут быть индивидуально адаптированы к вашим целям body-sculpting. Мы с радостью проконсультируем вас в нашей студии в Мюнхене-Хайдхаузен по лучшим синергиям для максимальных результатов.'
        },
        {
          q: isGerman ? 'Gibt es Ausfallzeiten nach der Kavitation?' : 'Есть ли период реабилитации после кавитации?',
          a: isGerman
            ? 'Nein, es gibt absolut keine Ausfallzeiten nach der Kavitation! Anders als bei der Liposuktion (2–4 Wochen Ausfallzeit mit Schmerzen, Schwellungen, Kompressionskleidung) können Sie sofort nach der Behandlung Ihrem normalen Alltag nachgehen, arbeiten gehen, Auto fahren oder leichten Sport treiben. Die Haut kann unmittelbar nach der Behandlung leicht gerötet sein oder sich warm anfühlen, was aber innerhalb von 30–60 Minuten vollständig abklingt. Es gibt keine Narben, keine Blutergüsse, keine Schwellungen, keine Schmerzen. Manche Kunden berichten von einem leichten „Druck- oder Völlegefühl" in der behandelten Zone, was durch die freigesetzten Fettsäuren verursacht wird — dies ist normal und verschwindet innerhalb von 24 Stunden. Das macht Kavitation ideal für berufstätige Menschen und alle, die eine effektive Body-Contouring-Methode ohne Einschränkungen suchen.'
            : 'Нет, абсолютно никакого периода реабилитации после кавитации! В отличие от липосакции (2–4 недели реабилитации с болями, отёками, компрессионной одеждой), вы можете сразу после процедуры вернуться к обычной жизни, идти на работу, водить машину или заниматься лёгким спортом. Кожа сразу после процедуры может быть слегка покрасневшей или тёплой на ощупь, но это полностью проходит в течение 30–60 минут. Нет рубцов, синяков, отёков, болей. Некоторые клиенты отмечают лёгкое «чувство давления или наполненности» в обработанной зоне, которое вызвано высвобожденными жирными кислотами — это нормально и исчезает в течение 24 часов. Это делает кавитацию идеальной для работающих людей и всех, кто ищет эффективный метод body-contouring без ограничений.'
        },
        {
          q: isGerman ? 'Für wen ist Kavitation geeignet?' : 'Для кого подходит кавитация?',
          a: isGerman
            ? 'Kavitation ist geeignet für Frauen und Männer mit normalem oder leicht erhöhtem BMI (18–30), die hartnäckige Fettpolster („Problemzonen") haben, die sich trotz gesunder Ernährung und regelmäßigem Sport nicht reduzieren lassen. Typische Problemzonen: Bauch (Unterbauch, „Love Handles"), Hüften („Reiterhosen"), Oberschenkel (Innen- und Außenseite), Gesäß, Oberarme, Knie, unterer Rücken. Kavitation ist auch ideal nach Schwangerschaft oder Gewichtsverlust zur Feinmodellierung. Nicht geeignet ist Kavitation bei starkem Übergewicht (BMI > 30), Schwangerschaft, Leber-/Nierenerkrankungen, Herzschrittmachern, Thrombose/Krampfadern und einigen anderen medizinischen Zuständen (siehe Kontraindikationen). Wir besprechen alle Kontraindikationen in der kostenlosen Beratung in unserem Kosmetikstudio in München.'
            : 'Кавитация подходит для женщин и мужчин с нормальным или слегка повышенным ИМТ (18–30), у которых есть упорные жировые отложения («проблемные зоны»), которые не уменьшаются несмотря на здоровое питание и регулярные занятия спортом. Типичные проблемные зоны: живот (нижний живот, «ушки»), бёдра («галифе»), бедра (внутренняя и наружная сторона), ягодицы, плечи, колени, нижняя часть спины. Кавитация также идеальна после беременности или похудения для точной коррекции. Не подходит кавитация при сильном избыточном весе (ИМТ > 30), беременности, заболеваниях печени/почек, кардиостимуляторе, тромбозе/варикозе и некоторых других медицинских состояниях (см. противопоказания). Мы обсуждаем все противопоказания на бесплатной консультации в нашей косметологической студии в Мюнхене.'
        },
        {
          q: isGerman ? 'Was kostet Kavitation in München?' : 'Сколько стоит кавитация в Мюнхене?',
          a: isGerman
            ? 'Die Preise variieren je nach Behandlungszone und Umfang: 🔹 Kavitation eine Zone (Bauch, Gesäß, Oberschenkel, 40 Min.) kostet 60€. 🔹 Kavitation zwei Zonen (60 Min.) kostet 95€. 🔹 Kavitation kleine Zone (Arme, Knie, 30 Min.) kostet 45€. 🔹 Kavitation + Lymphdrainage-Massage (75 Min.) kostet 120€. 🔹 Kavitation + RF-Lifting Körper (90 Min.) kostet 150€. Wir bieten attraktive Kur-Pakete an: 5er-Kur (eine Zone) für 270€ (spart 30€), 8er-Kur (eine Zone) für 420€ (spart 60€), 10er-Kur (eine Zone) für 500€ (spart 100€). Mit den Kur-Paketen sparen Sie nicht nur Geld, sondern sichern sich auch nachhaltige, langfristige Ergebnisse. Die Investition lohnt sich — Kavitation ist eine der kosteneffektivsten nicht-invasiven Body-Contouring-Methoden mit wissenschaftlich bewährter Wirkung und deutlich günstiger als eine Liposuktion.'
            : 'Цены варьируются в зависимости от зоны обработки и объёма: 🔹 Кавитация одна зона (живот, ягодицы, бедро, 40 мин.) стоит 60€. 🔹 Кавитация две зоны (60 мин.) стоит 95€. 🔹 Кавитация малая зона (руки, колени, 30 мин.) стоит 45€. 🔹 Кавитация + лимфодренажный массаж (75 мин.) стоит 120€. 🔹 Кавитация + RF-лифтинг тела (90 мин.) стоит 150€. Мы предлагаем выгодные курсовые пакеты: курс 5 процедур (одна зона) за 270€ (экономия 30€), курс 8 процедур (одна зона) за 420€ (экономия 60€), курс 10 процедур (одна зона) за 500€ (экономия 100€). С курсовыми пакетами вы не только экономите деньги, но и обеспечиваете устойчивый, долговременный результат. Инвестиция оправдана — кавитация является одним из самых рентабельных неинвазивных методов body-contouring с научно доказанной эффективностью и значительно дешевле липосакции.'
        }
      ]}
      ctaTitle={isGerman ? "Bereit für eine schlanke, definierte Silhouette in München?" : "Готовы к стройному, очерченному силуэту в Мюнхене?"}
      ctaDescription={isGerman
        ? "Buchen Sie jetzt Ihre Ultraschallkavitation in unserem Kosmetikstudio in München-Haidhausen und verabschieden Sie sich von hartnäckigen Fettpolstern — effektiv, schmerzfrei, ohne Operation und mit wissenschaftlich bewährter Wirkung. Kostenlose Beratung inklusive!"
        : "Запишитесь сейчас на ультразвуковую кавитацию в нашей косметологической студии в Мюнхене-Хайдхаузен и попрощайтесь с упорными жировыми отложениями — эффективно, безболезненно, без операции и с научно доказанной эффективностью. Бесплатная консультация включена!"
      }
    />
  );
};

export default Kavitation;
