'use client'

import { ServicePageLayout } from '@/components/ServicePageLayout';
import { Waves } from 'lucide-react';
import Link from 'next/link';
import { useLanguage } from '@/contexts/LanguageContext';

const Ultraschall = () => {
  const { isGerman } = useLanguage();

  // Custom sections component for procedure links
  const UltraschallProcedures = () => (
    <div className="space-y-6">
      <h2 className="text-3xl font-heading font-bold text-brand-espresso mb-8">
        {isGerman ? 'Unsere Ultraschall-Behandlungen in München' : 'Наши ультразвуковые процедуры в Мюнхене'}
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Phonophorese */}
        <Link href="/services/phonophorese" className="group">
          <div className="h-full p-6 bg-white rounded-lg border-2 border-brand-gold/20 hover:border-brand-gold transition-all duration-300 hover:shadow-lg">
            <h3 className="text-xl font-heading font-semibold text-brand-espresso mb-3 group-hover:text-brand-gold transition-colors">
              {isGerman ? 'Ultraschall-Phonophorese' : 'Ультразвуковая фонофорез'}
            </h3>
            <p className="text-brand-espresso/80 mb-4">
              {isGerman
                ? 'Tiefe Einschleusung von hochwertigen Wirkstoffen (Hyaluronsäure, Kollagen, Vitamine, Exosomen) mithilfe von Ultraschallwellen. Bis zu 10-fach tiefere Penetration für maximale Anti-Aging-Wirkung, intensive Hydratation und Hautregeneration.'
                : 'Глубокое введение активных веществ (гиалуроновая кислота, коллаген, витамины, экзосомы) при помощи ультразвука. Проникновение в 10 раз глубже для максимального омолаживающего эффекта, интенсивного увлажнения и регенерации кожи.'
              }
            </p>
            <span className="text-brand-gold font-semibold group-hover:underline">
              {isGerman ? 'Mehr erfahren →' : 'Узнать больше →'}
            </span>
          </div>
        </Link>

        {/* Kavitation */}
        <Link href="/services/koerperbehandlungen/kavitation" className="group">
          <div className="h-full p-6 bg-white rounded-lg border-2 border-brand-gold/20 hover:border-brand-gold transition-all duration-300 hover:shadow-lg">
            <h3 className="text-xl font-heading font-semibold text-brand-espresso mb-3 group-hover:text-brand-gold transition-colors">
              {isGerman ? 'Ultraschall-Kavitation' : 'Ультразвуковая кавитация'}
            </h3>
            <p className="text-brand-espresso/80 mb-4">
              {isGerman
                ? 'Nicht-invasive Körperformung durch Ultraschall-Fettreduktion. Die hochfrequenten Ultraschallwellen erzeugen Mikroblasen, die Fettzellen sanft auflösen. Ideal für Bauch, Hüften, Oberschenkel und andere Problemzonen – ohne OP, ohne Schmerzen.'
                : 'Неинвазивная коррекция фигуры через ультразвуковое разрушение жировых клеток. Высокочастотные ультразвуковые волны создают микропузырьки, которые мягко растворяют жир. Идеально для живота, бёдер, галифе — без операции, без боли.'
              }
            </p>
            <span className="text-brand-gold font-semibold group-hover:underline">
              {isGerman ? 'Mehr erfahren →' : 'Узнать больше →'}
            </span>
          </div>
        </Link>

        {/* Gesichtsreinigung */}
        <Link href="/services/gesichtsreinigung" className="group">
          <div className="h-full p-6 bg-white rounded-lg border-2 border-brand-gold/20 hover:border-brand-gold transition-all duration-300 hover:shadow-lg">
            <h3 className="text-xl font-heading font-semibold text-brand-espresso mb-3 group-hover:text-brand-gold transition-colors">
              {isGerman ? 'Ultraschall-Gesichtsreinigung' : 'Ультразвуковая чистка лица'}
            </h3>
            <p className="text-brand-espresso/80 mb-4">
              {isGerman
                ? 'Sanfte, aber gründliche Tiefenreinigung der Haut mit Ultraschallwellen. Entfernt sanft abgestorbene Hautzellen, Talg, Unreinheiten und Mitesser, verfeinert die Poren und stimuliert den Zellstoffwechsel – völlig schmerzfrei und ohne Hautschäden.'
                : 'Мягкая, но тщательная глубокая очистка кожи ультразвуковыми волнами. Деликатно удаляет ороговевшие клетки, кожное сало, загрязнения и комедоны, сужает поры и стимулирует клеточный обмен — абсолютно безболезненно и без повреждений кожи.'
              }
            </p>
            <span className="text-brand-gold font-semibold group-hover:underline">
              {isGerman ? 'Mehr erfahren →' : 'Узнать больше →'}
            </span>
          </div>
        </Link>
      </div>

      <div className="mt-8 p-6 bg-brand-gold/5 rounded-lg border border-brand-gold/20">
        <p className="text-brand-espresso/90 leading-relaxed">
          {isGerman
            ? '💡 Alle drei Verfahren nutzen die gleiche physikalische Grundlage — die Wirkung von Ultraschallwellen — unterscheiden sich jedoch in der Frequenz, Intensität, Tiefe, Behandlungszielen und verwendeten Präparaten. Während Phonophorese auf intensive Wirkstoffeinschleusung und Anti-Aging abzielt, dient Kavitation der Körperformung und Fettreduktion, und Ultraschall-Gesichtsreinigung der gründlichen, aber sanften Hautreinigung und Porenverfeinerung.'
            : '💡 Все три метода используют одну и ту же физическую основу — действие ультразвуковых волн, но различаются по частоте, интенсивности, глубине, целям воздействия и применяемым препаратам. В то время как фонофорез направлен на интенсивное введение активных веществ и омоложение, кавитация служит для коррекции фигуры и липолиза, а ультразвуковая чистка лица — для глубокого, но деликатного очищения и сужения пор.'
          }
        </p>
      </div>
    </div>
  );

  return (
    <ServicePageLayout
      icon={Waves}
      title={isGerman ? "Ultraschalltherapie in München — Moderne Technologien für Hautpflege und Regeneration" : "Ультразвуковая терапия в Мюнхене — Современные технологии ухода и восстановления"}
      subtitle={isGerman ? "Wissenschaftlich bewährte, nicht-invasive Behandlungen für Gesicht und Körper in München-Haidhausen" : "Научно обоснованные, неинвазивные процедуры для лица и тела в Мюнхене-Хайдхаузен"}
      aboutTitle={isGerman ? "Was ist Ultraschalltherapie und wie funktioniert sie?" : "Что такое ультразвуковая терапия и как она работает?"}
      aboutDescription={[
        isGerman
          ? 'Ultraschalltherapie ist eine moderne, wissenschaftlich fundierte Methode der Physiotherapie und ästhetischen Kosmetologie, bei der hochfrequente Schallwellen (20.000 bis 3.000.000 Hz) gezielt auf Haut und Gewebe einwirken. Diese für das menschliche Ohr unhörbaren Schwingungen erzeugen sanfte Mikrovibrationen in den tieferen Hautschichten, die eine Vielzahl positiver biologischer Effekte auslösen. In unserem Kosmetikstudio in München-Haidhausen setzen wir professionelle, medizinisch zertifizierte Ultraschallgeräte ein, die höchste Sicherheit und maximale Wirksamkeit garantieren.'
          : 'Ультразвуковая терапия — это современный, научно обоснованный метод физиотерапии и эстетической косметологии, при котором высокочастотные звуковые волны (от 20 000 до 3 000 000 Гц) целенаправленно воздействуют на кожу и ткани. Эти неслышимые для человеческого уха колебания создают мягкие микровибрации в глубоких слоях кожи, которые запускают множество положительных биологических эффектов. В нашей косметологической студии в Мюнхене-Хайдхаузен мы используем профессиональное, медицински сертифицированное ультразвуковое оборудование, которое гарантирует максимальную безопасность и эффективность.',

        isGerman
          ? 'Die Ultraschallwellen wirken auf zellulärer Ebene: Sie verbessern die Mikrozirkulation von Blut und Lymphe, aktivieren den Zellstoffwechsel und die Sauerstoffversorgung, stimulieren die Produktion von Kollagen und Elastin (den „Bausteinen" junger Haut), fördern die Regeneration geschädigter Zellen und wirken entzündungshemmend sowie schmerzlindernd. Gleichzeitig erzeugen die Ultraschallwellen eine Art „Mikromassage" der Haut, die Verspannungen löst, die Hautstruktur verfeinert und den natürlichen Entgiftungsprozess (Lymphdrainage) unterstützt.'
          : 'Ультразвуковые волны воздействуют на клеточном уровне: они улучшают микроциркуляцию крови и лимфы, активируют клеточный метаболизм и снабжение кислородом, стимулируют производство коллагена и эластина (строительных блоков молодой кожи), способствуют регенерации поврежденных клеток и оказывают противовоспалительное и обезболивающее действие. Одновременно ультразвуковые волны создают своеобразный «микромассаж» кожи, который снимает напряжение, улучшает текстуру кожи и поддерживает естественный процесс детоксикации (лимфодренаж).',

        isGerman
          ? 'Ein besonderer Vorteil der Ultraschalltherapie besteht darin, dass sie die Zellmembranen vorübergehend durchlässiger macht (Sonophorese-Effekt). Dies ermöglicht es, kosmetische und medizinische Wirkstoffe — wie Hyaluronsäure, Kollagen, Vitamine, Peptide oder hochmoderne Exosomen — bis zu 10-mal tiefer in die Haut einzuschleusen, als es mit herkömmlichen Methoden möglich wäre. Dadurch können diese Wirkstoffe dort wirken, wo sie am dringendsten benötigt werden: in den tiefen Schichten der Dermis.'
          : 'Особое преимущество ультразвуковой терапии заключается в том, что она временно делает клеточные мембраны более проницаемыми (эффект сонофореза). Это позволяет вводить косметические и медицинские активные вещества — такие как гиалуроновая кислота, коллаген, витамины, пептиды или современные экзосомы — в 10 раз глубже в кожу, чем это возможно при использовании обычных методов. Благодаря этому эти вещества могут действовать там, где они больше всего необходимы: в глубоких слоях дермы.',

        isGerman
          ? 'Die Ultraschalltherapie wird in der Medizin und ästhetischen Kosmetik seit Jahrzehnten erfolgreich eingesetzt und hat ihre Wirksamkeit in zahlreichen wissenschaftlichen Studien bewiesen. Sie ist völlig schmerzfrei, sicher, nicht-invasiv (ohne Injektionen oder Schnitte) und eignet sich für alle Hauttypen und Altersgruppen. Anders als invasive Verfahren gibt es keine Ausfallzeiten, keine Rötungen und kein Risiko für Komplikationen — Sie können direkt nach der Behandlung Ihrem normalen Alltag nachgehen.'
          : 'Ультразвуковая терапия уже несколько десятилетий успешно применяется в медицине и эстетической косметологии и доказала свою эффективность в многочисленных научных исследованиях. Она абсолютно безболезненна, безопасна, неинвазивна (без инъекций или разрезов) и подходит для всех типов кожи и возрастов. В отличие от инвазивных процедур, здесь нет периода реабилитации, покраснений и риска осложнений — вы можете сразу после процедуры вернуться к обычной жизни.',

        isGerman
          ? 'In unserem Kosmetikstudio in München bieten wir drei verschiedene Arten von Ultraschall-Behandlungen an, die alle auf der gleichen wissenschaftlichen Grundlage basieren, sich jedoch in ihren Zielen und Anwendungsbereichen unterscheiden: Ultraschall-Phonophorese für intensive Anti-Aging-Pflege und Wirkstoffeinschleusung, Ultraschall-Kavitation für nicht-invasive Körperformung und Fettreduktion sowie Ultraschall-Gesichtsreinigung für sanfte, aber gründliche Tiefenreinigung der Haut.'
          : 'В нашей косметологической студии в Мюнхене мы предлагаем три различных вида ультразвуковых процедур, которые основаны на одной и той же научной базе, но различаются по целям и областям применения: ультразвуковая фонофорез для интенсивного омоложения и введения активных веществ, ультразвуковая кавитация для неинвазивной коррекции фигуры и липолиза, а также ультразвуковая чистка лица для деликатного, но глубокого очищения кожи.'
      ]}
      benefits={[
        isGerman ? 'Verbesserung der Mikrozirkulation und Sauerstoffversorgung der Haut' : 'Улучшение микроциркуляции и снабжения кожи кислородом',
        isGerman ? 'Stimulation der Kollagen- und Elastinproduktion für straffere, jugendlichere Haut' : 'Стимуляция производства коллагена и эластина для более упругой, молодой кожи',
        isGerman ? 'Bis zu 10-fach tiefere Wirkstoffpenetration bei Phonophorese' : 'Проникновение активных веществ в 10 раз глубже при фонофорезе',
        isGerman ? 'Aktivierung des Zellstoffwechsels und Beschleunigung der Regeneration' : 'Активация клеточного метаболизма и ускорение регенерации',
        isGerman ? 'Lymphdrainage-Effekt für Entgiftung und Reduzierung von Schwellungen' : 'Лимфодренажный эффект для детоксикации и уменьшения отёков',
        isGerman ? 'Sanfte Mikromassage zur Entspannung der Gesichtsmuskulatur' : 'Мягкий микромассаж для расслабления лицевых мышц',
        isGerman ? 'Entzündungshemmende und schmerzlindernde Wirkung' : 'Противовоспалительное и обезболивающее действие',
        isGerman ? 'Porenverfeinerung und Verbesserung der Hautstruktur' : 'Сужение пор и улучшение текстуры кожи',
        isGerman ? 'Nicht-invasive Körperformung und Fettreduktion bei Kavitation' : 'Неинвазивная коррекция фигуры и липолиз при кавитации',
        isGerman ? 'Tiefenreinigung ohne mechanische Belastung der Haut' : 'Глубокое очищение без механического травмирования кожи',
        isGerman ? 'Völlig schmerzfrei, sicher und entspannend' : 'Абсолютно безболезненно, безопасно и расслабляюще',
        isGerman ? 'Keine Ausfallzeiten — sofort gesellschaftsfähig' : 'Без периода реабилитации — сразу готовы к общению',
        isGerman ? 'Kombinierbar mit anderen Behandlungen (Mikrostrom, RF, LED-Lichttherapie)' : 'Можно комбинировать с другими процедурами (микротоки, RF, светотерапия)',
        isGerman ? 'Geeignet für alle Hauttypen und Altersgruppen' : 'Подходит для всех типов кожи и возрастов',
        isGerman ? 'Wissenschaftlich bewährte Methode mit Jahrzehnten klinischer Erfahrung' : 'Научно обоснованный метод с десятилетиями клинического опыта',
        isGerman ? 'Natürliche, nicht-invasive Alternative zu Injektionen und operativen Eingriffen' : 'Естественная, неинвазивная альтернатива инъекциям и операциям'
      ]}
      steps={[
        {
          title: isGerman ? '1. Kostenlose Beratung und Hautanalyse' : '1. Бесплатная консультация и анализ кожи',
          description: isGerman
            ? 'Zu Beginn analysieren wir Ihren Hauttyp, Ihre Hautprobleme (Falten, Trockenheit, Unreinheiten, Pigmentierung, Schwellungen etc.) und Ihre individuellen Behandlungsziele. Basierend auf dieser Analyse empfehlen wir Ihnen die optimale Ultraschall-Behandlung: Phonophorese für Anti-Aging und intensive Pflege, Kavitation für Körperformung oder Ultraschall-Gesichtsreinigung für gründliche Hautreinigung. Wir besprechen auch mögliche Kombinationen mit anderen Behandlungen wie Mikrostromtherapie, RF-Lifting oder LED-Lichttherapie.'
            : 'В начале мы анализируем ваш тип кожи, проблемы (морщины, сухость, несовершенства, пигментация, отёки и т.д.) и индивидуальные цели. На основе этого анализа мы рекомендуем оптимальную ультразвуковую процедуру: фонофорез для омоложения и интенсивного ухода, кавитацию для коррекции фигуры или ультразвуковую чистку лица для глубокого очищения. Мы также обсуждаем возможные комбинации с другими процедурами, такими как микротоки, RF-лифтинг или светотерапия.'
        },
        {
          title: isGerman ? '2. Vorbereitung der Haut' : '2. Подготовка кожи',
          description: isGerman
            ? 'Die Haut wird sanft, aber gründlich von Make-up, Talg, Schmutz und abgestorbenen Hautzellen befreit. Eine saubere Haut ist essentiell für die optimale Wirkung der Ultraschallbehandlung. Anschließend wird ein spezielles Kontaktgel aufgetragen, das die Übertragung der Ultraschallwellen optimiert und ein angenehmes Gleiten des Ultraschallkopfes ermöglicht. Bei Phonophorese werden zusätzlich hochwertige Wirkstoffe (Seren, Ampullen) aufgetragen, die mit dem Ultraschall in die Tiefe eingeschleust werden.'
            : 'Кожа деликатно, но тщательно очищается от макияжа, кожного сала, загрязнений и ороговевших клеток. Чистая кожа необходима для оптимального эффекта ультразвука. Затем наносится специальный контактный гель, который оптимизирует передачу ультразвуковых волн и обеспечивает комфортное скольжение датчика. При фонофорезе дополнительно наносятся высококачественные активные вещества (сыворотки, ампулы), которые с помощью ультразвука проникают в глубокие слои кожи.'
        },
        {
          title: isGerman ? '3. Ultraschall-Behandlung (30-60 Minuten)' : '3. Ультразвуковая процедура (30-60 минут)',
          description: isGerman
            ? 'Mit einem speziellen Ultraschallkopf (Schallkopf) werden sanfte, kreisende Bewegungen über die Haut ausgeführt. Die hochfrequenten Schallwellen dringen in die tieferen Hautschichten ein und entfalten dort ihre vielfältigen positiven Wirkungen: Sie verbessern die Durchblutung, aktivieren den Stoffwechsel, stimulieren die Kollagenproduktion und fördern die Regeneration. Die Behandlung ist völlig schmerzfrei und wird von den meisten Kunden als sehr angenehm und entspannend empfunden — Sie spüren lediglich eine sanfte Wärme und leichte Vibrationen. Die Behandlungsdauer variiert je nach gewählter Methode: Phonophorese 60-75 Min., Kavitation 30-60 Min., Gesichtsreinigung als Teil einer umfassenden Gesichtsbehandlung.'
            : 'Специальным ультразвуковым датчиком выполняются мягкие круговые движения по коже. Высокочастотные звуковые волны проникают в глубокие слои кожи и оказывают там множественное положительное воздействие: улучшают кровообращение, активируют метаболизм, стимулируют производство коллагена и способствуют регенерации. Процедура абсолютно безболезненна и большинством клиентов воспринимается как очень приятная и расслабляющая — вы чувствуете лишь мягкое тепло и лёгкие вибрации. Продолжительность процедуры варьируется в зависимости от выбранного метода: фонофорез 60-75 мин., кавитация 30-60 мин., чистка лица как часть комплексной процедуры для лица.'
        },
        {
          title: isGerman ? '4. Abschlusspflege und optionale Kombinationen' : '4. Завершающий уход и опциональные комбинации',
          description: isGerman
            ? 'Nach der Ultraschallbehandlung tragen wir eine beruhigende, nährende Maske oder ein hochwertiges Serum auf, um die Regeneration zu unterstützen und den Behandlungseffekt zu verstärken und zu versiegeln. Optional kann die Ultraschalltherapie mit anderen Behandlungen kombiniert werden, um den Anti-Aging-Effekt, die Straffung oder die Tiefenreinigung zu maximieren: Mikrostromtherapie (für zusätzlichen Lifting-Effekt), LED-Lichttherapie (zur Beruhigung und Kollagenstimulation), RF-Lifting (für intensive Straffung) oder hochwertige Ampullen und Masken. Wir beraten Sie gerne zu den besten Kombinationen für Ihre individuellen Hautbedürfnisse.'
            : 'После ультразвуковой процедуры мы наносим успокаивающую питательную маску или высококачественную сыворотку, чтобы поддержать регенерацию и усилить и закрепить эффект процедуры. Опционально ультразвуковую терапию можно комбинировать с другими процедурами для максимизации омолаживающего эффекта, лифтинга или глубокого очищения: микротоки (для дополнительного лифтинга), светотерапия (для успокоения и стимуляции коллагена), RF-лифтинг (для интенсивной подтяжки) или высококачественные ампулы и маски. Мы с радостью проконсультируем вас по лучшим комбинациям для ваших индивидуальных потребностей.'
        },
        {
          title: isGerman ? '5. Pflegeempfehlungen und Behandlungsplan' : '5. Рекомендации по уходу и план процедур',
          description: isGerman
            ? 'Sie erhalten individuelle Empfehlungen für Ihre häusliche Pflege sowie einen Plan für Folgebehandlungen. Für optimale und langanhaltende Ergebnisse empfehlen wir je nach Behandlungsart eine Kur von 6-10 Behandlungen (Phonophorese, Gesichtsreinigung) bzw. 8-12 Behandlungen (Kavitation), gefolgt von regelmäßigen Erhaltungsbehandlungen. Bei Kavitation ist es wichtig, ausreichend Wasser zu trinken und sich moderat zu bewegen, um die Ausscheidung der aufgelösten Fettzellen über das Lymphsystem zu unterstützen.'
            : 'Вы получаете индивидуальные рекомендации по домашнему уходу, а также план последующих процедур. Для оптимального и долговременного результата мы рекомендуем в зависимости от типа процедуры курс из 6-10 процедур (фонофорез, чистка лица) или 8-12 процедур (кавитация), после чего регулярные поддерживающие сеансы. При кавитации важно пить достаточно воды и умеренно двигаться, чтобы поддержать выведение растворённых жировых клеток через лимфатическую систему.'
        }
      ]}
      // Add custom section for procedures
      additionalSections={<UltraschallProcedures />}
      // No price table - redirect to individual services
      priceTable={[]}
      contraindications={[
        isGerman ? 'Schwangerschaft' : 'Беременность',
        isGerman ? 'Herzschrittmacher oder Metallimplantate im Behandlungsbereich' : 'Кардиостимулятор или металлические имплантаты в зоне воздействия',
        isGerman ? 'Thrombose oder schwere Venenerkrankungen' : 'Тромбоз или тяжёлые заболевания вен',
        isGerman ? 'Krebs oder Chemotherapie' : 'Онкология или химиотерапия',
        isGerman ? 'Epilepsie' : 'Эпилепсия',
        isGerman ? 'Aktive Hautinfektionen, Herpes oder offene Wunden' : 'Активные кожные инфекции, герпес или открытые раны',
        isGerman ? 'Frische Operationen (mind. 3-6 Monate Abstand)' : 'Недавние операции (мин. 3-6 месяцев после)',
        isGerman ? 'Frische Filler oder Botox (mind. 2 Wochen Abstand)' : 'Недавние филлеры или ботокс (мин. 2 недели после)'
      ]}
      faq={[
        {
          q: isGerman ? 'Was ist der Unterschied zwischen Phonophorese, Kavitation und Ultraschall-Gesichtsreinigung?' : 'В чём разница между фонофорезом, кавитацией и ультразвуковой чисткой лица?',
          a: isGerman
            ? 'Alle drei Verfahren nutzen Ultraschallwellen, unterscheiden sich jedoch in Frequenz, Intensität und Zielsetzung: 🔹 Ultraschall-Phonophorese (1-3 MHz) schleust hochwertige Wirkstoffe (Hyaluronsäure, Kollagen, Vitamine, Exosomen) bis zu 10-mal tiefer in die Haut ein — ideal für Anti-Aging, intensive Hydratation und Hautregeneration. 🔹 Ultraschall-Kavitation (40 kHz) erzeugt Mikroblasen im Fettgewebe, die Fettzellen sanft auflösen — ideal für nicht-invasive Körperformung und Fettreduktion an Bauch, Hüften, Oberschenkeln. 🔹 Ultraschall-Gesichtsreinigung (20-30 kHz) entfernt sanft abgestorbene Hautzellen, Talg und Unreinheiten — ideal für gründliche, aber schonende Tiefenreinigung und Porenverfeinerung.'
            : 'Все три метода используют ультразвуковые волны, но различаются по частоте, интенсивности и целям: 🔹 Ультразвуковая фонофорез (1-3 МГц) вводит высококачественные активные вещества (гиалуроновая кислота, коллаген, витамины, экзосомы) в 10 раз глубже в кожу — идеально для омоложения, интенсивного увлажнения и регенерации кожи. 🔹 Ультразвуковая кавитация (40 кГц) создаёт микропузырьки в жировой ткани, которые мягко растворяют жировые клетки — идеально для неинвазивной коррекции фигуры и липолиза на животе, бёдрах, галифе. 🔹 Ультразвуковая чистка лица (20-30 кГц) деликатно удаляет ороговевшие клетки, кожное сало и загрязнения — идеально для глубокого, но щадящего очищения и сужения пор.'
        },
        {
          q: isGerman ? 'Ist Ultraschalltherapie schmerzhaft oder gefährlich?' : 'Ультразвуковая терапия болезненна или опасна?',
          a: isGerman
            ? 'Nein, die Ultraschalltherapie ist völlig schmerzfrei, sicher und wird von den meisten Kunden als sehr angenehm und entspannend empfunden. Sie spüren lediglich eine sanfte Wärme und leichte Vibrationen auf der Haut. Die Methode wird seit Jahrzehnten in der Medizin und ästhetischen Kosmetik eingesetzt und hat ihre Sicherheit in zahlreichen wissenschaftlichen Studien bewiesen. Anders als invasive Verfahren gibt es keine Injektionen, keine Schnitte, keine Ausfallzeiten und kein Risiko für Komplikationen. Die einzigen Kontraindikationen sind Schwangerschaft, Herzschrittmacher, Thrombose und einige andere medizinische Zustände, die wir in der Beratung besprechen.'
            : 'Нет, ультразвуковая терапия абсолютно безболезненна, безопасна и большинством клиентов воспринимается как очень приятная и расслабляющая. Вы чувствуете лишь мягкое тепло и лёгкие вибрации на коже. Метод применяется десятилетиями в медицине и эстетической косметологии и доказал свою безопасность в многочисленных научных исследованиях. В отличие от инвазивных процедур, здесь нет инъекций, разрезов, периода реабилитации и риска осложнений. Единственные противопоказания — беременность, кардиостимулятор, тромбоз и некоторые другие медицинские состояния, которые мы обсуждаем на консультации.'
        },
        {
          q: isGerman ? 'Wie viele Behandlungen brauche ich für sichtbare Ergebnisse?' : 'Сколько процедур нужно для видимого результата?',
          a: isGerman
            ? 'Die Anzahl der Behandlungen hängt von der gewählten Methode und Ihren individuellen Zielen ab: ✅ Phonophorese: Erste Ergebnisse (prallere, strahlendere Haut) bereits nach 1-2 Behandlungen sichtbar. Für nachhaltige Anti-Aging-Effekte empfehlen wir eine Kur von 8-10 Behandlungen, 1-2× pro Woche, gefolgt von Erhaltungsbehandlungen 1× pro Monat. ✅ Kavitation: Erste Verbesserungen nach 3-4 Behandlungen spürbar. Für optimale Körperformung und Fettreduktion empfehlen wir 8-12 Behandlungen, 1× pro Woche, ggf. gefolgt von Erhaltungsbehandlungen alle 2-3 Monate. ✅ Gesichtsreinigung: Sofortiger Effekt nach jeder Behandlung (frischere, reinere Haut). Für langfristig reine, porenverfeinerung Haut empfehlen wir 1× alle 4-6 Wochen.'
            : 'Количество процедур зависит от выбранного метода и ваших индивидуальных целей: ✅ Фонофорез: Первые результаты (более упругая, сияющая кожа) видны уже после 1-2 процедур. Для устойчивого омолаживающего эффекта мы рекомендуем курс из 8-10 процедур, 1-2× в неделю, после чего поддерживающие сеансы 1× в месяц. ✅ Кавитация: Первые улучшения ощутимы после 3-4 процедур. Для оптимальной коррекции фигуры и липолиза мы рекомендуем 8-12 процедур, 1× в неделю, при необходимости с последующими поддерживающими сеансами каждые 2-3 месяца. ✅ Чистка лица: Мгновенный эффект после каждой процедуры (более свежая, чистая кожа). Для долгосрочной чистой кожи с суженными порами мы рекомендуем 1× каждые 4-6 недель.'
        },
        {
          q: isGerman ? 'Kann ich Ultraschalltherapie mit anderen Behandlungen kombinieren?' : 'Можно ли комбинировать ультразвуковую терапию с другими процедурами?',
          a: isGerman
            ? 'Ja, die Ultraschalltherapie lässt sich hervorragend mit anderen Behandlungen kombinieren und verstärkt deren Wirkung erheblich! Besonders empfehlenswerte Kombinationen: 🔸 Ultraschall + Mikrostromtherapie = maximaler Lifting-Effekt und Straffung. 🔸 Ultraschall + LED-Lichttherapie = intensive Kollagenstimulation und Beruhigung. 🔸 Ultraschall + RF-Lifting = tiefenwirksame Straffung und Anti-Aging. 🔸 Phonophorese + Gesichtsreinigung = perfekte Vorbereitung + intensive Wirkstoffeinschleusung. 🔸 Kavitation + Lymphdrainage-Massage = beschleunigte Fettausscheidung und Entgiftung. Die Kombination verstärkt die Synergie-Effekte und kann individuell auf Ihre Hautbedürfnisse abgestimmt werden. Wir beraten Sie gerne in unserem Studio in München-Haidhausen zu den besten Kombinationen.'
            : 'Да, ультразвуковую терапию можно отлично комбинировать с другими процедурами, что значительно усиливает их эффект! Особенно рекомендуемые комбинации: 🔸 Ультразвук + микротоки = максимальный лифтинг-эффект и подтяжка. 🔸 Ультразвук + светотерапия = интенсивная стимуляция коллагена и успокоение. 🔸 Ультразвук + RF-лифтинг = глубокая подтяжка и омоложение. 🔸 Фонофорез + чистка лица = идеальная подготовка + интенсивное введение активных веществ. 🔸 Кавитация + лимфодренажный массаж = ускоренное выведение жира и детоксикация. Комбинация усиливает синергетические эффекты и может быть индивидуально адаптирована к вашим потребностям. Мы с радостью проконсультируем вас в нашей студии в Мюнхене-Хайдхаузен по лучшим комбинациям.'
        },
        {
          q: isGerman ? 'Gibt es Ausfallzeiten nach einer Ultraschallbehandlung?' : 'Есть ли период реабилитации после ультразвуковой процедуры?',
          a: isGerman
            ? 'Nein, es gibt absolut keine Ausfallzeiten nach einer Ultraschallbehandlung! Anders als bei invasiven Verfahren (Laser, IPL, Injektionen) können Sie direkt nach der Behandlung Ihrem normalen Alltag nachgehen, Make-up auftragen, arbeiten gehen oder Sport treiben. Die Haut kann maximal leicht gerötet sein (besonders nach Kavitation oder intensiver Gesichtsreinigung), was aber innerhalb von 1-2 Stunden vollständig abklingt. Bei Kavitation empfehlen wir, in den folgenden 24-48 Stunden ausreichend Wasser zu trinken (mind. 2 Liter) und sich moderat zu bewegen, um die Ausscheidung der aufgelösten Fettzellen über das Lymphsystem zu unterstützen. Das macht die Ultraschalltherapie ideal für berufstätige Menschen und alle, die eine schnelle, effektive Behandlung ohne Einschränkungen suchen.'
            : 'Нет, абсолютно никакого периода реабилитации после ультразвуковой процедуры! В отличие от инвазивных процедур (лазер, IPL, инъекции), вы можете сразу после процедуры вернуться к обычной жизни, наносить макияж, идти на работу или заниматься спортом. Кожа может быть максимум слегка покрасневшей (особенно после кавитации или интенсивной чистки лица), но это полностью проходит в течение 1-2 часов. При кавитации мы рекомендуем в течение следующих 24-48 часов пить достаточно воды (мин. 2 литра) и умеренно двигаться, чтобы поддержать выведение растворённых жировых клеток через лимфатическую систему. Это делает ультразвуковую терапию идеальной для работающих людей и всех, кто ищет быструю, эффективную процедуру без ограничений.'
        },
        {
          q: isGerman ? 'Für wen ist Ultraschalltherapie geeignet?' : 'Для кого подходит ультразвуковая терапия?',
          a: isGerman
            ? 'Ultraschalltherapie ist für fast alle Hauttypen und Altersgruppen geeignet: ✅ Phonophorese: für alle ab Mitte 20 mit ersten Alterungserscheinungen, trockener Haut, Pigmentierung oder dem Wunsch nach intensiver Hautpflege und Prävention. ✅ Kavitation: für alle ab 18 mit lokalen Fettdepots (Bauch, Hüften, Oberschenkel), die sich trotz Sport und Diät nicht reduzieren lassen — ideal als nicht-invasive Alternative zur Fettabsaugung. ✅ Gesichtsreinigung: für alle Hauttypen, besonders bei unreiner, zu Akne neigender Haut, verstopften Poren oder als regelmäßige Tiefenreinigung. Nicht geeignet ist Ultraschall bei Schwangerschaft, Herzschrittmachern, Thrombose, Epilepsie und einigen anderen medizinischen Zuständen. Wir besprechen alle Kontraindikationen in der kostenlosen Beratung in unserem Kosmetikstudio in München.'
            : 'Ультразвуковая терапия подходит практически для всех типов кожи и возрастов: ✅ Фонофорез: для всех с середины 20-х с первыми признаками старения, сухой кожей, пигментацией или желанием интенсивного ухода и профилактики. ✅ Кавитация: для всех с 18 лет с локальными жировыми отложениями (живот, бёдра, галифе), которые не уходят несмотря на спорт и диету — идеально как неинвазивная альтернатива липосакции. ✅ Чистка лица: для всех типов кожи, особенно при проблемной коже, склонной к акне, забитых порах или как регулярное глубокое очищение. Не подходит ультразвук при беременности, кардиостимуляторе, тромбозе, эпилепсии и некоторых других медицинских состояниях. Мы обсуждаем все противопоказания на бесплатной консультации в нашей косметологической студии в Мюнхене.'
        },
        {
          q: isGerman ? 'Was kostet Ultraschalltherapie in München?' : 'Сколько стоит ультразвуковая терапия в Мюнхене?',
          a: isGerman
            ? 'Die Preise variieren je nach gewählter Behandlung: 🔹 Ultraschall-Phonophorese: ab 85€ für Gesicht (60 Min.), ab 105€ für Gesicht + Hals + Dekolleté (75 Min.), ab 150€ für Premium-Variante mit Exosomen. Kur-Pakete: 3× für 230€, 5× für 360€. 🔹 Ultraschall-Kavitation: ab 60€ pro Zone (30-45 Min.), Mehrfachzonen günstiger. Kur-Pakete für optimale Ergebnisse verfügbar. 🔹 Ultraschall-Gesichtsreinigung: ab 95€ für kombinierte Gesichtsreinigung (90 Min.), ab 140€ in Kombination mit Phonophorese. Die genauen Preise und Kur-Angebote finden Sie auf den jeweiligen Seiten unserer Ultraschall-Behandlungen oder in unserem Studio in München-Haidhausen. Wir beraten Sie gerne individuell und erstellen Ihnen ein maßgeschneidertes Behandlungskonzept.'
            : 'Цены варьируются в зависимости от выбранной процедуры: 🔹 Ультразвуковая фонофорез: от 85€ за лицо (60 мин.), от 105€ за лицо + шея + декольте (75 мин.), от 150€ за премиум-вариант с экзосомами. Курсовые пакеты: 3× за 230€, 5× за 360€. 🔹 Ультразвуковая кавитация: от 60€ за зону (30-45 мин.), при работе с несколькими зонами дешевле. Доступны курсовые пакеты для оптимального результата. 🔹 Ультразвуковая чистка лица: от 95€ за комбинированную чистку лица (90 мин.), от 140€ в сочетании с фонофорезом. Точные цены и курсовые предложения вы найдёте на соответствующих страницах наших ультразвуковых процедур или в нашей студии в Мюнхене-Хайдхаузен. Мы с радостью проконсультируем вас индивидуально и составим персонализированную концепцию процедур.'
        }
      ]}
      ctaTitle={isGerman ? "Bereit für moderne Ultraschalltherapie in München?" : "Готовы к современной ультразвуковой терапии в Мюнхене?"}
      ctaDescription={isGerman
        ? "Entdecken Sie die vielfältigen Möglichkeiten der Ultraschalltherapie in unserem Kosmetikstudio in München-Haidhausen: intensive Anti-Aging-Pflege mit Phonophorese, nicht-invasive Körperformung mit Kavitation oder gründliche Gesichtsreinigung — alles schmerzfrei, sicher und mit wissenschaftlich bewährter Wirkung. Kostenlose Beratung inklusive!"
        : "Откройте для себя разнообразные возможности ультразвуковой терапии в нашей косметологической студии в Мюнхене-Хайдхаузен: интенсивный омолаживающий уход с фонофорезом, неинвазивная коррекция фигуры с кавитацией или глубокая чистка лица — всё безболезненно, безопасно и с научно доказанной эффективностью. Бесплатная консультация включена!"
      }
    />
  );
};

export default Ultraschall;
